MinGW support (#2360)
* Add MinGW support (not full yet).

TODO list:
* Fix tests compilation (undefined reference to CppUnit::...)
* Fix SQLs compilation (No rule to make target '${LIBNAME}.dll.a', needed by '${LIBNAME}.dll'.  Stop.)
* Fix crypto executables compilation
* Test static compilation
* Test MSVC compilation
* Add unicode support

See pocoproject/poco#2356

* Code rearrange.

Also fix PDF test runner.

TODO list:
* Fix tests compilation (undefined reference to CppUnit::...)
* Add unicode support
* Resolve what to do with message compiler

See pocoproject/poco#2356

* Normal "_DLL" definition for MinGW. Add missing "Crypto_API" for several implementations. Add "POCO_NO_MINGW_UNICODE" for "wmain".

TODO list:
* Check PostgreSQL and MySQL
* Resolve what to do with message compiler

See pocoproject/poco#2356

* Test PostgreSQL. Fix message compiler problem.

See pocoproject/poco#2356

* Perform requested changes. Add WinCE check.

See pocoproject/poco#2360

* Perform requested changes #2. Delete WinCE check.

See pocoproject/poco#2360

* Perform requested changes #3. Net initializer should works now.

See pocoproject/poco#2360

* Fix invalid indent.

See pocoproject/poco#2360

* Correct definition of POCO_NO_MINGW_UNICODE.

See pocoproject/poco#2360

* Remove macro and set global linke flags for testing purpose

* Add -municode for mingw where wmain is used

* Delete "POCO_ENABLE_EXE_WMAIN". Add PollSet support.

See pocoproject/poco#2360

* Restore WinCE linker flags. Set _WIN32_WINNT in PollSet.cpp separately. Add var to disable MinGW wmain wrapper.

* Fix compilation.

* Fix missing argument name in functions "setEscapeUnicode" in JSON package.