Fix warnings with release 1.9.0 and gcc 9:
/remote/intdeliv/components/osp/Poco/Foundation/19-0-0-2/include/Poco/Dynamic/VarHolder.h: In instantiation of ‘void Poco::Dynamic::VarHolder::checkUpperLimit(const F&) const [with F = short int; T = signed char]’:
/remote/intdeliv/components/osp/Poco/Foundation/19-0-0-2/include/Poco/Dynamic/VarHolder.h:327:4:   required from ‘void Poco::Dynamic::VarHolder::convertToSmaller(const F&, T&) const [with F = short int; T = signed char]’
/remote/intdeliv/components/osp/Poco/Foundation/19-0-0-2/include/Poco/Dynamic/VarHolder.h:913:29:   required from here
/remote/intdeliv/components/osp/Poco/Foundation/19-0-0-2/include/Poco/Dynamic/VarHolder.h:435:39: error: comparison of integer expressions of different signedness: ‘Poco::UInt64’ {aka ‘long unsigned int’} and ‘signed char’ [-Werror=sign-compare]
  435 |       static_cast<Poco::UInt64>(from) > std::numeric_limits<T>::max())
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~