Fix conflicting declaration with unbundled pcre
Building poco 1.6.1 with the `--unbundled` config options fails due to an
conflicting declaration of `pcre`:

```sh
In file included from src/RegularExpression.cpp:21:0:
/usr/include/pcre.h:325:26: error: conflicting declaration ‘typedef struct real_pcre pcre’
 typedef struct real_pcre pcre;
                          ^
In file included from src/RegularExpression.cpp:17:0:
include/Poco/RegularExpression.h:37:34: note: previous declaration as ‘typedef struct real_pcre8_or_16 pcre’
  typedef struct real_pcre8_or_16 pcre;
```